In [1]:
import numpy as np

In [2]:
q1_rev = np.array([2,5,8])
print(q1_rev)
print(f"Dimension:{q1_rev.ndim}")
print(f"Bytes:{q1_rev.nbytes}")
print(f"Size:{q1_rev.size}")
print(f"Data Type:{q1_rev.dtype}")
print(f"{q1_rev.dtype}")

[2 5 8]
Dimension:1
Bytes:24
Size:3
Data Type:int64
int64


In [3]:
revenue = np.array([[2,5,8],[2,1,10],[9,15,20],[10,11,12]])

print(revenue)
print(revenue.ndim)
print(revenue.nbytes)
print(revenue.size)
print(revenue.dtype)
print(revenue.itemsize)

[[ 2  5  8]
 [ 2  1 10]
 [ 9 15 20]
 [10 11 12]]
2
96
12
int64
8


In [4]:
print(revenue.shape)


(4, 3)


In [5]:
np.sort(revenue)


array([[ 2,  5,  8],
       [ 1,  2, 10],
       [ 9, 15, 20],
       [10, 11, 12]])

In [6]:
revenue


array([[ 2,  5,  8],
       [ 2,  1, 10],
       [ 9, 15, 20],
       [10, 11, 12]])

In [7]:
np.sort(revenue, axis=0)


array([[ 2,  1,  8],
       [ 2,  5, 10],
       [ 9, 11, 12],
       [10, 15, 20]])

In [8]:
np.sort(revenue, axis=1)


array([[ 2,  5,  8],
       [ 1,  2, 10],
       [ 9, 15, 20],
       [10, 11, 12]])

In [9]:
np.sort(revenue, axis=None)

array([ 1,  2,  2,  5,  8,  9, 10, 10, 11, 12, 15, 20])

In [10]:
zero_arr = np.zeros((3,4),'int16')
zero_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [11]:
zero_arr.dtype

dtype('int16')

In [12]:
one_arr = np.ones((4,5),'int16')
one_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [13]:
np.arange(50,0,-3)

array([50, 47, 44, 41, 38, 35, 32, 29, 26, 23, 20, 17, 14, 11,  8,  5,  2])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
revenue

array([[ 2,  5,  8],
       [ 2,  1, 10],
       [ 9, 15, 20],
       [10, 11, 12]])

In [16]:
revenue.flatten()

array([ 2,  5,  8,  2,  1, 10,  9, 15, 20, 10, 11, 12])

In [17]:
revenue

array([[ 2,  5,  8],
       [ 2,  1, 10],
       [ 9, 15, 20],
       [10, 11, 12]])

In [18]:
revenue.reshape((6,2))

array([[ 2,  5],
       [ 8,  2],
       [ 1, 10],
       [ 9, 15],
       [20, 10],
       [11, 12]])

In [19]:
revenue.sum(axis=0)

array([23, 32, 50])

In [20]:
revenue.sum(axis=1)

array([15, 13, 44, 33])

### looping over numpy array

In [21]:
for row in revenue:
    print(row)

[2 5 8]
[ 2  1 10]
[ 9 15 20]
[10 11 12]


In [22]:
for row in revenue:
    for element in row:
        print(f"product revenue {element}mln$")

product revenue 2mln$
product revenue 5mln$
product revenue 8mln$
product revenue 2mln$
product revenue 1mln$
product revenue 10mln$
product revenue 9mln$
product revenue 15mln$
product revenue 20mln$
product revenue 10mln$
product revenue 11mln$
product revenue 12mln$
