# Operations on matrices

<img src="./matrix-numpy.jpg" alt="Matrix Example Image" style="width:75%">

In [1]:
import numpy as np

In [2]:
q1 = np.array([[200,250,190],[100,180,145],[210,350,280]])
q1

array([[200, 250, 190],
       [100, 180, 145],
       [210, 350, 280]])

In [3]:
q2 = np.array([[250,180,195],[90,185,130],[235,200,215]])
q2

array([[250, 180, 195],
       [ 90, 185, 130],
       [235, 200, 215]])

In [4]:
# Find sum of product sold in both quarter

print(f"Sum of units sold in each region: \n{q1+q2}")

Sum of units sold in each region: 
[[450 430 385]
 [190 365 275]
 [445 550 495]]


In [5]:
# Find sales unit groth from q1 to q2
print(f"unit growth in sale of product from q1 to q2: \n{q2-q1}")

unit growth in sale of product from q1 to q2: 
[[  50  -70    5]
 [ -10    5  -15]
 [  25 -150  -65]]


In [6]:
# Find percentage growth in sales unit from q1 to q2
print(f"Percentage growth % in sale of product from q1 to q2: \n{((q2-q1)/q1)*100}")

Percentage growth % in sale of product from q1 to q2: 
[[ 25.         -28.           2.63157895]
 [-10.           2.77777778 -10.34482759]
 [ 11.9047619  -42.85714286 -23.21428571]]


<img src="./prices.jpeg" alt="Product Prices" style="width:75%">

In [7]:
prices = np.array([
    [2,1.13,1.15],
    [2.5,1.8,1.95],
    [3,2.25,2.2]])

prices

array([[2.  , 1.13, 1.15],
       [2.5 , 1.8 , 1.95],
       [3.  , 2.25, 2.2 ]])

In [8]:
q1_revenue = q1 * prices
q1_revenue

array([[400.  , 282.5 , 218.5 ],
       [250.  , 324.  , 282.75],
       [630.  , 787.5 , 616.  ]])

## COGS (Cost of Goods Sold) -> Per piece

In [9]:
cogs = np.array([
    [0.9,1.12,1],
    [1.13,1.5,1.25],
    [1.8,1.6,1.7]
])
cogs

array([[0.9 , 1.12, 1.  ],
       [1.13, 1.5 , 1.25],
       [1.8 , 1.6 , 1.7 ]])

In [13]:
q1_cogs = q1*cogs
q1_cogs

array([[180.  , 280.  , 190.  ],
       [113.  , 270.  , 181.25],
       [378.  , 560.  , 476.  ]])

## Calculate Gross Profit

In [14]:
gross_profit = q1_revenue - q1_cogs
gross_profit

array([[220. ,   2.5,  28.5],
       [137. ,  54. , 101.5],
       [252. , 227.5, 140. ]])

## Product Example

In [15]:
#builder
# 1 column means sqft, 2 column means bhk 
features = np.array(
    [
        [3500,3],
        [2800,2],
        [2000,1],
        [1200,1]
    ]
)
features

array([[3500,    3],
       [2800,    2],
       [2000,    1],
       [1200,    1]])

In [11]:
prices

array([[2.  , 1.13, 1.15],
       [2.5 , 1.8 , 1.95],
       [3.  , 2.25, 2.2 ]])

In [16]:
# 1 column means per sqft price, 2 column means additional price for each bedroom
prices = np.array([150,50000])
prices

array([  150, 50000])

In [17]:
price_3bhk = 150*3500+3*50000
print("Price of flat for 3bhk: =",price_3bhk)

Price of flat for 3bhk: = 675000


In [18]:
final_prices = np.dot(features,prices)
final_prices

array([675000, 520000, 350000, 230000])