<h1 style = 'color:blue'><b><u>Slicing and Stacking</u><</b></h1>

<br>

# Slicing


In [1]:
import numpy as np


In [2]:
arr = np.array([2,8,16,35,-6,-5])
arr

array([ 2,  8, 16, 35, -6, -5])

In [3]:
arr.ndim


1

In [4]:
arr[3]


np.int64(35)

In [5]:
arr[1:4]

array([ 8, 16, 35])

In [6]:
arr[::2]

array([ 2, 16, -6])

In [7]:
arr = np.array(
    [
        [2,80,16,45,-3],
        [8,90,-6,-3,18],
        [-1,-3,-5,32,48],
        [8,12,-9,-6,-3]
    ]
)
arr

array([[ 2, 80, 16, 45, -3],
       [ 8, 90, -6, -3, 18],
       [-1, -3, -5, 32, 48],
       [ 8, 12, -9, -6, -3]])

In [8]:
arr.ndim

2

In [9]:
arr[2]

array([-1, -3, -5, 32, 48])

In [10]:
arr[2][3]

np.int64(32)

In [11]:
arr[2,1:4]

array([-3, -5, 32])

In [12]:
arr[:,1:4]


array([[80, 16, 45],
       [90, -6, -3],
       [-3, -5, 32],
       [12, -9, -6]])

# Stacking

In [14]:
student_info = np.array([
    [1,"Rohan"],
    [2,"Pranjal"],
    [3,"Rohit"],
])
student_info

array([['1', 'Rohan'],
       ['2', 'Pranjal'],
       ['3', 'Rohit']], dtype='<U21')

In [15]:
course_info = np.array([
    [1,"C++"],
    [2,"JAVA"],
    [3,"C++"],
])
course_info

array([['1', 'C++'],
       ['2', 'JAVA'],
       ['3', 'C++']], dtype='<U21')

In [16]:
np.hstack((course_info,course_info))

array([['1', 'C++', '1', 'C++'],
       ['2', 'JAVA', '2', 'JAVA'],
       ['3', 'C++', '3', 'C++']], dtype='<U21')